import type { Metadata } from 'next';
import { Atkinson_Hyperlegible, Inter, Poppins } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/navbar/Navbar';

const inter = Inter({ subsets: ['latin'] });

const poppins = Poppins({
	weight: ['300', '400', '700'],
	style: ['normal'],
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const atkinson = Atkinson_Hyperlegible({
	weight: ['700'],
	style: ['normal'],
	subsets: ['latin']
});

export default function RootLayout({
									   children
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body className={atkinson.className}>
		<main className="min-h-screen flex flex-col items-center bg-white">
			<Navbar></Navbar>
			{children}
		</main>
		</body>
		</html>
	);
}
